"""initial schema

Revision ID: 71abb196dea8
Revises: 
Create Date: 2026-09-25 22:55:02.184053
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '71abb196dea8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('workflow', sa.String(length=64), nullable=False),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('evaluator', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_run_id'), 'failures', ['run_id'], unique=False)
    op.create_table('repairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('failure_id', sa.String(length=36), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repairs_run_id'), 'repairs', ['run_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_event_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_event_id'], ['agent_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_repairs_run_id'), table_name='repairs')
    op.drop_table('repairs')
    op.drop_index(op.f('ix_failures_run_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
