"""failure attribution fields

Revision ID: b82e95a85792
Revises: 71abb196dea8
Create Date: 2026-09-25 23:20:17.178971
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b82e95a85792'
down_revision: str | None = '71abb196dea8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('recommended_action', sa.Text(), nullable=True))
    op.add_column('failures', sa.Column('attribution_method', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'attribution_method')
    op.drop_column('failures', 'recommended_action')
    # ### end Alembic commands ###
